# Generated by Django 5.2.1 on 2025-06-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketmodel',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
