# Generated by Django 5.2.1 on 2025-06-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_marketmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketmodel',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
