# Generated by Django 5.2 on 2025-06-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('ShopOwner', 'ShopOwner')], default='Customer', max_length=20),
        ),
    ]
