# Generated by Django 5.2 on 2025-06-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmodel',
            name='floor',
            field=models.CharField(choices=[('1', 'first'), ('2', 'secound'), ('3', 'third'), ('4', 'fourth'), ('5', 'five'), ('6', 'six'), ('7', 'seven'), ('8', 'eight')], max_length=10),
        ),
    ]
