# Generated by Django 5.2 on 2025-06-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shopmodel_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmodel',
            name='floor',
            field=models.CharField(choices=[('first', 'first'), ('secound', 'secound'), ('third', 'third'), ('fourth', 'fourth'), ('five', 'five'), ('six', 'six'), ('seven', 'seven'), ('eight', 'eight')], max_length=10),
        ),
    ]
