# Generated by Django 5.2 on 2025-06-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shopmodel_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmodel',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
