# Generated by Django 5.2 on 2025-06-05 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_marketmodel_name'),
        ('shop', '0005_itemmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='category',
            field=models.CharField(choices=[('Man', 'Man'), ('Women', 'Women'), ('Kids', 'Kids'), ('Sport', 'Sport'), ('All', 'All')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='shopmodel',
            constraint=models.UniqueConstraint(fields=('name', 'market'), name='unique_shop_name_in_market'),
        ),
    ]
