# Generated by Django 5.2 on 2025-06-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_itemmodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
